
#Activation / désactivation des modules TetraLibs (serveur)
[modules]
	bck_core = true
	bck_backpack = true
	bck_home = true
	bck_permissions = true
	bck_recipe = true
	bck_skill = true
	bck_spawn = true
	bck_lich_eye = true
	bck_lich_clear = true
	bck_lich_whisper = true
	bck_serverdata = true
	bck_userdata = true
	bck_economy_manager = true
	bck_warps = true
	bck_leveling = true
	bck_combat = true
	bck_lich_guard = false

